output: html
onlyCategories:
  - performance
  - accessibility
  - seo
  - best-practices
logLevel: info
thresholds:
  performance: 0.5
  accessibility: 0.7
  seo: 0.7
  best-practices: 0.7
reportPath: lighthouse-report/custom-lighthouse-report.html